### ISSUE TITLE
Issues with Llama-3.2-11B-Vision-Instruct

### ISSUE THREAD

**Issue by AshviniKSharma** [dottxt-ai/outlines#1294]
### Describe the issue as clearly as possible:

Unable to work with Llama-3.2-11B-Vision-Instruct, getting CUDA Out of Bounds Issue

### Steps/code to reproduce the bug:

```python
# LLM stuff
import outlines
import torch
from transformers import AutoProcessor, MllamaForConditionalGeneration
from pydantic import BaseModel, Field
from typing import Literal, Optional, List

# Image stuff
from PIL import Image
import matplotlib.pyplot as plt
import json

from rich import print

model_name = "meta-llama/Llama-3.2-11B-Vision-Instruct"
model_class = MllamaForConditionalGeneration

model = outlines.models.transformers_vision(
    model_name,
    model_class=model_class,
    model_kwargs={
        "device_map": "cuda:0",
        "torch_dtype": torch.bfloat16,
    },
    processor_kwargs={
        "device": "cuda:0", # set to "cpu" if you don't have a GPU
    },
)


# Set up the content you want to send to the model
messages = [
    {
        "role": "user",
        "content": [
            {
                # The image is provided as a PIL Image object
                "type": "image",
                "image": image,
            },
            {
                "type": "text",
                "text": f"""You are an expert at extracting information from PAN Card.
                Please extract the information from the PAN Card. Be as detailed as possible --
                missing or misreporting information is a crime.

                Return the information in the following JSON schema:
                {Recipt.model_json_schema()}
            """},
        ],
    }
]

# Convert the messages to the final prompt
processor = AutoProcessor.from_pretrained(model_name)
prompt = processor.apply_chat_template(
    messages, tokenize=False, add_generation_prompt=True
)

# Prepare a function to process receipts
receipt_summary_generator = outlines.generate.json(
    model,
    Recipt,

    # Greedy sampling is a good idea for numeric
    # data extraction -- no randomness.
    sampler=outlines.samplers.greedy()
)

# Generate the receipt summary
result = receipt_summary_generator(prompt, [image])
print(result)
```

### Expected result:

```shell
Should print JSON
```

### Error message:

```shell
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [145,0,0], thread: [116,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[12], [line 12](vscode-notebook-cell:?execution_count=12&line=12)
      [2](vscode-notebook-cell:?execution_count=12&line=2) receipt_summary_generator = outlines.generate.json(
      [3](vscode-notebook-cell:?execution_count=12&line=3)     model,
      [4](vscode-notebook-cell:?execution_count=12&line=4)     Recipt,
   (...)
      [8](vscode-notebook-cell:?execution_count=12&line=8)     sampler=outlines.samplers.greedy()
      [9](vscode-notebook-cell:?execution_count=12&line=9) )
     [11](vscode-notebook-cell:?execution_count=12&line=11) # Generate the receipt summary
---> [12](vscode-notebook-cell:?execution_count=12&line=12) result = receipt_summary_generator(prompt, [image])
     [13](vscode-notebook-cell:?execution_count=12&line=13) print(result)

File ~/miniconda3/envs/outlines/lib/python3.9/site-packages/outlines/generate/api.py:556, in VisionSequenceGeneratorAdapter.__call__(self, prompts, media, max_tokens, stop_at, seed, **model_specific_params)
    [550](https://vscode-remote+ssh-002dremote-002bphx-002dscavenge.vscode-resource.vscode-cdn.net/home/ashvshar/madrid/friendly/Outlines/~/miniconda3/envs/outlines/lib/python3.9/site-packages/outlines/generate/api.py:550) prompts, media = self._validate_prompt_media_types(prompts, media)
    [552](https://vscode-remote+ssh-002dremote-002bphx-002dscavenge.vscode-resource.vscode-cdn.net/home/ashvshar/madrid/friendly/Outlines/~/miniconda3/envs/outlines/lib/python3.9/site-packages/outlines/generate/api.py:552) generation_params = self.prepare_generation_parameters(
    [553](https://vscode-remote+ssh-002dremote-002bphx-002dscavenge.vscode-resource.vscode-cdn.net/home/ashvshar/madrid/friendly/Outlines/~/miniconda3/envs/outlines/lib/python3.9/site-packages/outlines/generate/api.py:553)     max_tokens, stop_at, seed
    [554](https://vscode-remote+ssh-002dremote-002bphx-002dscavenge.vscode-resource.vscode-cdn.net/home/ashvshar/madrid/friendly/Outlines/~/miniconda3/envs/outlines/lib/python3.9/site-packages/outlines/generate/api.py:554) )
--> [556](https://vscode-remote+ssh-002dremote-002bphx-002dscavenge.vscode-resource.vscode-cdn.net/home/ashvshar/madrid/friendly/Outlines/~/miniconda3/envs/outlines/lib/python3.9/site-packages/outlines/generate/api.py:556) completions = self.model.generate(
    [557](https://vscode-remote+ssh-002dremote-002bphx-002dscavenge.vscode-resource.vscode-cdn.net/home/ashvshar/madrid/friendly/Outlines/~/miniconda3/envs/outlines/lib/python3.9/site-packages/outlines/generate/api.py:557)     prompts,
    [558](https://vscode-remote+ssh-002dremote-002bphx-002dscavenge.vscode-resource.vscode-cdn.net/home/ashvshar/madrid/friendly/Outlines/~/miniconda3/envs/outlines/lib/python3.9/site-packages/outlines/generate/api.py:558)     media,
    [559](https://vscode-remote+ssh-002dremote-002bphx-002dscavenge.vscode-resource.vscode-cdn.net/home/ashvshar/madrid/friendly/Outlines/~/miniconda3/envs/outlines/lib/python3.9/site-packages/outlines/generate/api.py:559)     generation_params,
    [560](https://vscode-remote+ssh-002dremote-002bphx-002dscavenge.vscode-resource.vscode-cdn.net/home/ashvshar/madrid/friendly/Outlines/~/miniconda3/envs/outlines/lib/python3.9/site-packages/outlines/generate/api.py:560)     copy(self.logits_processor),
    [561](https://vscode-remote+ssh-002dremote-002bphx-002dscavenge.vscode-resource.vscode-cdn.net/home/ashvshar/madrid/friendly/Outlines/~/miniconda3/envs/outlines/lib/python3.9/site-packages/outlines/generate/api.py:561)     self.sampling_params,
    [562](https://vscode-remote+ssh-002dremote-002bphx-002dscavenge.vscode-resource.vscode-cdn.net/home/ashvshar/madrid/friendly/Outlines/~/miniconda3/envs/outlines/lib/python3.9/site-packages/outlines/generate/api.py:562)     **model_specific_params,
...
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```
```


### Outlines/Python version information:

Version information
<details>
```
0.1.6
Python 3.9.20 (main, Oct  3 2024, 07:27:41) 
[GCC 11.2.0]
accelerate==1.1.1
aiohappyeyeballs==2.4.3
aiohttp==3.11.8
aiosignal==1.3.1
airportsdata==20241001
annotated-types==0.7.0
asttokens @ file:///opt/conda/conda-bld/asttokens_1646925590279/work
async-timeout==5.0.1
attrs==24.2.0
backcall @ file:///home/ktietz/src/ci/backcall_1611930011877/work
certifi==2024.8.30
charset-normalizer==3.4.0
cloudpickle==3.1.0
comm @ file:///croot/comm_1709322850197/work
contourpy==1.3.0
cycler==0.12.1
datasets==3.1.0
debugpy @ file:///croot/debugpy_1690905042057/work
decorator @ file:///opt/conda/conda-bld/decorator_1643638310831/work
dill==0.3.8
diskcache==5.6.3
exceptiongroup @ file:///croot/exceptiongroup_1706031385326/work
executing @ file:///opt/conda/conda-bld/executing_1646925071911/work
filelock==3.16.1
fonttools==4.55.0
frozenlist==1.5.0
fsspec==2024.9.0
huggingface-hub==0.26.2
idna==3.10
importlib_metadata @ file:///croot/importlib_metadata-suite_1732633488278/work
importlib_resources==6.4.5
interegular==0.3.3
ipykernel @ file:///croot/ipykernel_1728665589812/work
ipython @ file:///croot/ipython_1694181358621/work
jedi @ file:///croot/jedi_1721058342488/work
Jinja2==3.1.4
jsonschema==4.23.0
jsonschema-specifications==2024.10.1
jupyter_client @ file:///croot/jupyter_client_1699455897726/work
jupyter_core @ file:///croot/jupyter_core_1718818295206/work
kiwisolver==1.4.7
lark==1.2.2
markdown-it-py==3.0.0
MarkupSafe==3.0.2
matplotlib==3.9.2
matplotlib-inline @ file:///opt/conda/conda-bld/matplotlib-inline_1662014470464/work
mdurl==0.1.2
mpmath==1.3.0
multidict==6.1.0
multiprocess==0.70.16
nest-asyncio @ file:///croot/nest-asyncio_1708532673751/work
networkx==3.2.1
numpy==2.0.2
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==9.1.0.70
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.20.5
nvidia-nvjitlink-cu12==12.6.85
nvidia-nvtx-cu12==12.1.105
outlines @ git+https://github.com/dottxt-ai/outlines.git@e9485cf2126d9c14bd749d55f8aa6729d96808d0
outlines_core==0.1.17
packaging @ file:///croot/packaging_1720101850331/work
pandas==2.2.3
parso @ file:///opt/conda/conda-bld/parso_1641458642106/work
pexpect @ file:///tmp/build/80754af9/pexpect_1605563209008/work
pickleshare @ file:///tmp/build/80754af9/pickleshare_1606932040724/work
pillow==11.0.0
platformdirs @ file:///croot/platformdirs_1692205439124/work
prompt-toolkit @ file:///croot/prompt-toolkit_1704404351921/work
propcache==0.2.0
psutil @ file:///opt/conda/conda-bld/psutil_1656431268089/work
ptyprocess @ file:///tmp/build/80754af9/ptyprocess_1609355006118/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
pure-eval @ file:///opt/conda/conda-bld/pure_eval_1646925070566/work
pyarrow==18.1.0
pycountry==24.6.1
pydantic==2.10.2
pydantic_core==2.27.1
Pygments @ file:///croot/pygments_1684279966437/work
pyparsing==3.2.0
python-dateutil @ file:///croot/python-dateutil_1716495738603/work
pytz==2024.2
PyYAML==6.0.2
pyzmq @ file:///croot/pyzmq_1705605076900/work
referencing==0.35.1
regex==2024.11.6
requests==2.32.3
rich==13.9.4
rpds-py==0.21.0
safetensors==0.4.5
six @ file:///tmp/build/80754af9/six_1644875935023/work
stack-data @ file:///opt/conda/conda-bld/stack_data_1646927590127/work
sympy==1.13.3
tokenizers==0.20.3
torch==2.4.0
tornado @ file:///croot/tornado_1718740109488/work
tqdm==4.67.1
traitlets @ file:///croot/traitlets_1718227057033/work
transformers==4.46.3
triton==3.0.0
typing_extensions @ file:///croot/typing_extensions_1715268824938/work
tzdata==2024.2
urllib3==2.2.3
wcwidth @ file:///Users/ktietz/demo/mc3/conda-bld/wcwidth_1629357192024/work
xxhash==3.5.0
yarl==1.18.0
zipp @ file:///croot/zipp_1732630741423/work
```
</details>


### Context for the issue:

_No response_

**Comment by rlouf** [comment]
This does not seem to be an issue with `outlines`.

**Comment by AshviniKSharma** [comment]
Please let me know what information you need, as I am able to run LLaMA3.2 Vision without outlines without any issue. It would be great if you could provide a working example with LLAMA3.2 Vision, I will try it my end to check if everything is in check.

**Comment by cpfiffer** [comment]
This suggests that the issue is likely due to your CUDA installation, which is infamously awful to deal with.

```

File ~/miniconda3/envs/outlines/lib/python3.9/site-packages/outlines/processors/structured.py:121, in GuideLogitsProcessor.process_logits(self, input_ids, logits)
    [118](https://vscode-remote+ssh-002dremote-002bphx-002dscavenge.vscode-resource.vscode-cdn.net/home/ashvshar/madrid/friendly/Outlines/~/miniconda3/envs/outlines/lib/python3.9/site-packages/outlines/processors/structured.py:118) allowed_tokens_concat = torch.cat(allowed_tokens_batch)
    [119](https://vscode-remote+ssh-002dremote-002bphx-002dscavenge.vscode-resource.vscode-cdn.net/home/ashvshar/madrid/friendly/Outlines/~/miniconda3/envs/outlines/lib/python3.9/site-packages/outlines/processors/structured.py:119) batch_indices_concat = torch.cat(batch_indices)
--> [121](https://vscode-remote+ssh-002dremote-002bphx-002dscavenge.vscode-resource.vscode-cdn.net/home/ashvshar/madrid/friendly/Outlines/~/miniconda3/envs/outlines/lib/python3.9/site-packages/outlines/processors/structured.py:121) mask[batch_indices_concat, allowed_tokens_concat] = False
    [122](https://vscode-remote+ssh-002dremote-002bphx-002dscavenge.vscode-resource.vscode-cdn.net/home/ashvshar/madrid/friendly/Outlines/~/miniconda3/envs/outlines/lib/python3.9/site-packages/outlines/processors/structured.py:122) logits.masked_fill_(mask, float("-inf"))
    [124](https://vscode-remote+ssh-002dremote-002bphx-002dscavenge.vscode-resource.vscode-cdn.net/home/ashvshar/madrid/friendly/Outlines/~/miniconda3/envs/outlines/lib/python3.9/site-packages/outlines/processors/structured.py:124) return logits

RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

I've found [Perplexity](https://www.perplexity.ai/search/runtimeerror-cuda-error-device-s1RlbjsNSy.I9wp43.ZnbQ) to be pretty good at working through these issues, but I agree with Remi that this does not seem to be an Outlines issue.

**Comment by priyank9320** [comment]
Hi @cpfiffer, while trying to run the Llama-3.2-11B-Vision-Instruct with outlines on CPU i was able to get a better error msg:

> IndexError: index 128256 is out of bounds for dimension 1 with size 128256

And it turns out that this Input Id refers to the Image token in Llama and it is not used in generating the output which is indicated by the logits shape, therefore can be filtered out. Not an issue with outlines, but gives error with the mentioned Llama model.

I have created a pull request: https://github.com/dottxt-ai/outlines/pull/1310
(but this way we will be filtering out the input id every time so maybe there is a better way to do it)

Let me know your thoughts.

**Comment by jbbqqf** [comment]
Hi! Triaging — this report uses `outlines.models.transformers_vision(model_name, model_class=...)` to load Llama-3.2-Vision. That loader signature was removed in Outlines 1.0.

Evidence on current `main` (`6ae2135`):
- The v0 `models.transformers_vision(...)` loader is gone. The v1 equivalent loads the HF model/processor yourself and wraps them via `outlines.from_transformers(model, processor)`, which returns a `TransformersMultiModal` instance — see the class at https://github.com/dottxt-ai/outlines/blob/6ae21356fd0dda00afd0ef0e76752904a22fc0aa/outlines/models/transformers.py#L610 and the factory at https://github.com/dottxt-ai/outlines/blob/6ae21356fd0dda00afd0ef0e76752904a22fc0aa/outlines/models/transformers.py#L693.
- The traceback through `outlines/processors/structured.py::GuideLogitsProcessor.process_logits` references the v0 processor path; v1 processors live in https://github.com/dottxt-ai/outlines/blob/6ae21356fd0dda00afd0ef0e76752904a22fc0aa/outlines/processors and have been substantially restructured.
- For multimodal usage, see the v1 multimodal guide referenced from https://github.com/dottxt-ai/outlines/blob/6ae21356fd0dda00afd0ef0e76752904a22fc0aa/docs/guide/migration.md (Models section).

The original CUDA-out-of-bounds error around the image token (id 128256) was specific to how the v0 `transformers_vision` path constructed input ids; on v1 the user controls model + processor construction so the same path no longer applies. If the issue still reproduces on v1.x with `from_transformers(...)`, a fresh issue with a v1 reproducer would be much more actionable. Otherwise this can be closed as superseded.

---
*Disclosure: I drafted this comment with help from Claude Code while triaging stale issues on `outlines` v1.x. The code/doc references above were verified manually against `main` (`6ae2135`, current latest 1.3.0).*
